# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', picklefield.fields.PickledObjectField(editable=False, null=True)),
                ('verbose_name', models.CharField(max_length=255)),
            ],
        ),
    ]
